---
dist: xenial
language: python
python: "2.7"
# Use the new container infrastructure
sudo: true
# Install ansible
addons:
  apt:
    packages:
    - python-pip
install:
  # Install ansible
  - pip install ansible
  # Check ansible version
  - ansible --version
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg
script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Run the role with ansible-playbook.
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --become
  - kill %1
after_success:
  - ls -lrt /usr/local/src
